# Generated by Django 5.2.1 on 2025-05-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offerdetail',
            options={'ordering': ['offer_type']},
        ),
    ]
