# Generated by Django 5.2.1 on 2025-05-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coderr_app', '0002_businessprofile_customerprofile'),
        ('Coderr_app', '0003_migrate_profiles'),
    ]

    operations = [
    ]
